language: c
dist: xenial

addons:
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - libhdf5-openmpi-dev

before_install:
    - which gfortran
    - gfortran --version
    - which gcc
    - which h5dump

script:
    - set -e
    - cd ED/build/
    - ./install.sh -k C -p travisci -g
