name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends gfortran libhdf5-openmpi-dev libopenmpi-dev
    - name: Install ED2
      run: |
        cd ED/build
        ./install.sh -g -p travisci -k A
    - name: Upload compiled ED2 binary
      uses: actions/upload-artifact@v1
      with:
        name: ed2-binary
        path: ED/build/ed_2.1-dbg

  harvard-forest:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Retrieve compiled binary
      uses: actions/download-artifact@v1
      with:
        name: ed2-binary
    - name: Install dependencies
      run: sudo apt-get install -y --no-install-recommends gfortran libhdf5-openmpi-dev libopenmpi-dev
    - name: Download common ED2 files
      working-directory: ./EDTS/Templates/
      run: |
        wget https://github.com/ashiklom/edts-datasets/releases/download/common/common.tar.gz
        tar -xf common.tar.gz
    - name: Download Harvard Forest files
      working-directory: ./EDTS/Templates/
      run: |
        wget https://github.com/ashiklom/edts-datasets/releases/download/harvard-forest/harvard-forest.tar.gz
        tar -xf harvard-forest.tar.gz
    - name: Run ED2 at Harvard Forest
      working-directory: ./EDTS/Templates/
      run: |
        chmod +x "$GITHUB_WORKSPACE"/ed2-binary/ed_2.1-dbg
        ulimit -s unlimited
        OMP_NUM_THREADS=1 "$GITHUB_WORKSPACE"/ed2-binary/ed_2.1-dbg -s -f ED2IN-harvard-forest
